#!/usr/bin/env ruby

require "mercenary"

Mercenary.program(:cliYo) do |p|
  p.description 'CliYo is a program which can send Yo!s from the command line, at regular intervals'
  p.syntax "cli-yo <all your friends you wanna yo!> [options]"
  p.version "0.0.1"

  p.description "yo your friends from the command line"
  p.option 'silent', "-s" , '--silent', 'silently yo your friend while you proceed with your work!'
  p.option "count" , "-c COUNT" , "--count COUNT" , "how many times do you want to yo! your friend, defaults to 1"
  p.option "interval" , "-i INTERVAL" , "--interval INTERVAL" , "how often do you want to yo! your friend (in minutes) , defaults to 1"
  
  p.action do |args , options|
  	require "./cli_yo.rb"
  	options[:username] = args
  	Cli_Yo.yo! options
  end

end